# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 699)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1101, 681))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color:qlineargradient(x0:0,y1:0,x0:1,y2:2,stop:0 rgb(20,32,44),stop:1 rgb(32,85,117));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 211, 661))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.planet_create = QtWidgets.QPushButton(self.frame_3)
        self.planet_create.setMaximumSize(QtCore.QSize(16777215, 32))
        self.planet_create.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(165,205,255,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(165,205,255,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(165,205,255,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.planet_create.setObjectName("planet_create")
        self.verticalLayout.addWidget(self.planet_create)
        self.planet_list = QtWidgets.QListWidget(self.frame_3)
        self.planet_list.setMinimumSize(QtCore.QSize(0, 0))
        self.planet_list.setMouseTracking(False)
        self.planet_list.setFocusPolicy(QtCore.Qt.NoFocus)
        self.planet_list.setStyleSheet("QListView{\n"
"    border:none;\n"
"    background-color:rgba(255,255,255,10%);\n"
"    color:rgba(255,255,255,0.8);\n"
"}\n"
"QListView::item{\n"
"    background-color:transparent;\n"
"    height:40px;\n"
"    padding:5px;\n"
"    margin-bottom:5px;\n"
"}\n"
"QListView::item:hover{\n"
"    background-color:transparent;\n"
"    color:rgba(255,255,255,0.8);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color:rgba(255,255,255,35%);\n"
"    color:rgba(255,255,255,0.8);\n"
"    border-left:2px solid rgb(255,255,255);\n"
"    border-radius:18px\n"
"}\n"
"")
        self.planet_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planet_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.planet_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.planet_list.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.planet_list.setTabKeyNavigation(True)
        self.planet_list.setLayoutMode(QtWidgets.QListView.Batched)
        self.planet_list.setObjectName("planet_list")
        self.verticalLayout.addWidget(self.planet_list)
        self.planet_select = QtWidgets.QPushButton(self.frame_3)
        self.planet_select.setMaximumSize(QtCore.QSize(16777215, 32))
        self.planet_select.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(165,205,255,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(165,205,255,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(165,205,255,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.planet_select.setObjectName("planet_select")
        self.verticalLayout.addWidget(self.planet_select)
        self.planet_delete = QtWidgets.QPushButton(self.frame_3)
        self.planet_delete.setMaximumSize(QtCore.QSize(16777215, 32))
        self.planet_delete.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(205, 0, 0,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(205,0,0,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(205,0,0,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.planet_delete.setObjectName("planet_delete")
        self.verticalLayout.addWidget(self.planet_delete)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(690, 10, 401, 661))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 381, 401))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_11 = QtWidgets.QLabel(self.frame_8)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.label_11.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255, 0.8);\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    font:bold 16px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_11.setObjectName("label_11")
        self.view = QtWidgets.QGraphicsView(self.frame_8)
        self.view.setGeometry(QtCore.QRect(20, 40, 341, 341))
        self.view.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.view.setObjectName("view")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(10, 430, 381, 221))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_12 = QtWidgets.QLabel(self.frame_9)
        self.label_12.setGeometry(QtCore.QRect(20, 10, 131, 31))
        self.label_12.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,80%);\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    font:bold 16px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_12.setObjectName("label_12")
        self.lcd_ap = QtWidgets.QLCDNumber(self.frame_9)
        self.lcd_ap.setGeometry(QtCore.QRect(70, 50, 64, 23))
        self.lcd_ap.setObjectName("lcd_ap")
        self.label_15 = QtWidgets.QLabel(self.frame_9)
        self.label_15.setGeometry(QtCore.QRect(20, 50, 41, 21))
        self.label_15.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_9)
        self.label_16.setGeometry(QtCore.QRect(20, 90, 41, 21))
        self.label_16.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_9)
        self.label_17.setGeometry(QtCore.QRect(190, 50, 71, 21))
        self.label_17.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_17.setObjectName("label_17")
        self.lcd_pe = QtWidgets.QLCDNumber(self.frame_9)
        self.lcd_pe.setGeometry(QtCore.QRect(70, 90, 64, 23))
        self.lcd_pe.setObjectName("lcd_pe")
        self.lcd_v = QtWidgets.QLCDNumber(self.frame_9)
        self.lcd_v.setGeometry(QtCore.QRect(270, 50, 64, 23))
        self.lcd_v.setObjectName("lcd_v")
        self.label_18 = QtWidgets.QLabel(self.frame_9)
        self.label_18.setGeometry(QtCore.QRect(140, 50, 41, 21))
        self.label_18.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.frame_9)
        self.label_19.setGeometry(QtCore.QRect(140, 90, 41, 21))
        self.label_19.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(340, 50, 41, 21))
        self.label_20.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_20.setObjectName("label_20")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(230, 10, 451, 661))
        self.frame_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(10, 0, 431, 221))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(10, 170, 411, 51))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.calculate = QtWidgets.QPushButton(self.frame_14)
        self.calculate.setGeometry(QtCore.QRect(10, 12, 391, 31))
        self.calculate.setMaximumSize(QtCore.QSize(16777215, 32))
        self.calculate.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(43,162,239,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:15px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(43,162,239,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(43,162,239,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.calculate.setObjectName("calculate")
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 431, 171))
        self.frame_15.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.info_ap = QtWidgets.QLineEdit(self.frame_15)
        self.info_ap.setGeometry(QtCore.QRect(280, 40, 111, 21))
        self.info_ap.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.info_ap.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.info_ap.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.info_ap.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.info_ap.setAlignment(QtCore.Qt.AlignCenter)
        self.info_ap.setDragEnabled(False)
        self.info_ap.setReadOnly(False)
        self.info_ap.setObjectName("info_ap")
        self.label = QtWidgets.QLabel(self.frame_15)
        self.label.setGeometry(QtCore.QRect(250, 40, 21, 16))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_15)
        self.label_2.setGeometry(QtCore.QRect(250, 70, 21, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setGeometry(QtCore.QRect(250, 0, 111, 31))
        self.label_3.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_15)
        self.label_4.setGeometry(QtCore.QRect(250, 100, 21, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_15)
        self.label_5.setGeometry(QtCore.QRect(250, 130, 21, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.info_pe = QtWidgets.QLineEdit(self.frame_15)
        self.info_pe.setGeometry(QtCore.QRect(280, 70, 111, 21))
        self.info_pe.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.info_pe.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.info_pe.setAlignment(QtCore.Qt.AlignCenter)
        self.info_pe.setObjectName("info_pe")
        self.info_delta_t = QtWidgets.QLineEdit(self.frame_15)
        self.info_delta_t.setGeometry(QtCore.QRect(280, 100, 111, 21))
        self.info_delta_t.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.info_delta_t.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.info_delta_t.setAlignment(QtCore.Qt.AlignCenter)
        self.info_delta_t.setObjectName("info_delta_t")
        self.info_h = QtWidgets.QLineEdit(self.frame_15)
        self.info_h.setGeometry(QtCore.QRect(280, 130, 111, 21))
        self.info_h.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.info_h.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.info_h.setAlignment(QtCore.Qt.AlignCenter)
        self.info_h.setObjectName("info_h")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setGeometry(QtCore.QRect(400, 40, 21, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setGeometry(QtCore.QRect(400, 70, 21, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_15)
        self.label_8.setGeometry(QtCore.QRect(400, 100, 21, 16))
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_15)
        self.label_9.setGeometry(QtCore.QRect(400, 130, 21, 16))
        self.label_9.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.front = QtWidgets.QRadioButton(self.frame_15)
        self.front.setGeometry(QtCore.QRect(70, 140, 16, 19))
        self.front.setStyleSheet("")
        self.front.setText("")
        self.front.setObjectName("front")
        self.behind = QtWidgets.QRadioButton(self.frame_15)
        self.behind.setGeometry(QtCore.QRect(180, 140, 16, 19))
        self.behind.setStyleSheet("")
        self.behind.setText("")
        self.behind.setObjectName("behind")
        self.frame_5 = QtWidgets.QFrame(self.frame_15)
        self.frame_5.setGeometry(QtCore.QRect(140, 30, 101, 91))
        self.frame_5.setStyleSheet("image: url(:/图标/behind.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_15)
        self.frame_6.setGeometry(QtCore.QRect(40, 30, 81, 71))
        self.frame_6.setStyleSheet("image: url(:/图标/front.png);\n"
"background-color: rgba(255, 255, 255, 0);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_13 = QtWidgets.QLabel(self.frame_15)
        self.label_13.setGeometry(QtCore.QRect(30, 0, 101, 31))
        self.label_13.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_15)
        self.label_14.setGeometry(QtCore.QRect(140, 0, 101, 31))
        self.label_14.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,0.8);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(10, 220, 431, 441))
        self.frame_13.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_10 = QtWidgets.QLabel(self.frame_13)
        self.label_10.setGeometry(QtCore.QRect(20, 10, 71, 31))
        self.label_10.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255,80%);\n"
"    font-size:16px;\n"
"    font-weight:bold;\n"
"    font:bold 16px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_10.setObjectName("label_10")
        self.listWidget = QtWidgets.QListWidget(self.frame_13)
        self.listWidget.setGeometry(QtCore.QRect(10, 70, 411, 361))
        self.listWidget.setStyleSheet("QListView{\n"
"    border:none;\n"
"    background-color:rgba(255,255,255,0%);\n"
"    color:rgba(255,255,255,0.8);\n"
"}\n"
"QListView::item{\n"
"    background-color:transparent;\n"
"    height:40px;\n"
"    padding-left:4px;\n"
"}\n"
"QListView::item:hover{\n"
"    background-color:transparent;\n"
"    color:rgba(43,162,238,150);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color:transparent;\n"
"    color:rgb(43,162,238);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.plan = QtWidgets.QListWidget(self.frame_13)
        self.plan.setGeometry(QtCore.QRect(10, 50, 411, 381))
        self.plan.setMinimumSize(QtCore.QSize(0, 0))
        self.plan.setMouseTracking(False)
        self.plan.setFocusPolicy(QtCore.Qt.NoFocus)
        self.plan.setStyleSheet("QListView{\n"
"    border:none;\n"
"    background-color:rgba(255,255,255,10%);\n"
"    color:rgba(255,255,255,0.8);\n"
"}\n"
"QListView::item{\n"
"    background-color:transparent;\n"
"    height:40px;\n"
"    padding:5px;\n"
"    margin-bottom:5px;\n"
"}\n"
"QListView::item:hover{\n"
"    background-color:transparent;\n"
"    color:rgba(255,255,255,0.8);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color:rgba(255,255,255,35%);\n"
"    color:rgba(255,255,255,0.8);\n"
"    border-left:2px solid rgb(255,255,255);\n"
"    border-radius:18px\n"
"}\n"
"")
        self.plan.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plan.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plan.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plan.setEditTriggers(QtWidgets.QAbstractItemView.EditKeyPressed)
        self.plan.setTabKeyNavigation(True)
        self.plan.setLayoutMode(QtWidgets.QListView.Batched)
        self.plan.setObjectName("plan")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.planet_create.setText(_translate("Form", "创建星球"))
        self.planet_select.setText(_translate("Form", "选择星球"))
        self.planet_delete.setText(_translate("Form", "删除星球"))
        self.label_11.setText(_translate("Form", "变轨示意图"))
        self.label_12.setText(_translate("Form", "变轨方案详细信息"))
        self.label_15.setText(_translate("Form", "远地点"))
        self.label_16.setText(_translate("Form", "近地点"))
        self.label_17.setText(_translate("Form", "交会速度差"))
        self.label_18.setText(_translate("Form", "km"))
        self.label_19.setText(_translate("Form", "km"))
        self.label_20.setText(_translate("Form", "m/s"))
        self.calculate.setText(_translate("Form", "规划"))
        self.label.setText(_translate("Form", "AP"))
        self.label_2.setText(_translate("Form", "PE"))
        self.label_3.setText(_translate("Form", "变轨点信息"))
        self.label_4.setText(_translate("Form", "Δt"))
        self.label_5.setText(_translate("Form", "H"))
        self.label_6.setText(_translate("Form", "km"))
        self.label_7.setText(_translate("Form", "km"))
        self.label_8.setText(_translate("Form", "s"))
        self.label_9.setText(_translate("Form", "km"))
        self.label_13.setText(_translate("Form", "目标在前"))
        self.label_14.setText(_translate("Form", "目标在后"))
        self.label_10.setText(_translate("Form", "待选方案"))
import png_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
