# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1101, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1101, 681))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    background-color:qlineargradient(x0:0,y1:0,x0:1,y2:2,stop:0 rgb(20,32,44),stop:1 rgb(32,85,117));\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(10, 10, 211, 661))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(165,205,255,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(165,205,255,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(165,205,255,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.listWidget = QtWidgets.QListWidget(self.frame_3)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.listWidget.setStyleSheet("QListView{\n"
"    border:none;\n"
"    background-color:rgba(255,255,255,10%);\n"
"    color:rgd(255,255,255);\n"
"}\n"
"QListView::item{\n"
"    background-color:transparent;\n"
"    height:40px;\n"
"    padding-left:4px;\n"
"}\n"
"QListView::item:hover{\n"
"    background-color:transparent;\n"
"    color:rgba(43,162,238,150);\n"
"}\n"
"QListView::item:selected{\n"
"    background-color:transparent;\n"
"    color:rgb(43,162,238);\n"
"}\n"
"")
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_5.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(165,205,255,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(165,205,255,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(165,205,255,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_6.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(205, 0, 0,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:8px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(205,0,0,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(205,0,0,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout.addWidget(self.pushButton_6)
        spacerItem = QtWidgets.QSpacerItem(20, 265, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(690, 10, 401, 661))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(10, 10, 381, 401))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.frame_9 = QtWidgets.QFrame(self.frame_7)
        self.frame_9.setGeometry(QtCore.QRect(10, 430, 381, 221))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.frame_11 = QtWidgets.QFrame(self.frame)
        self.frame_11.setGeometry(QtCore.QRect(230, 10, 451, 661))
        self.frame_11.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setGeometry(QtCore.QRect(10, 0, 431, 221))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(10, 170, 411, 51))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_14)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 12, 391, 31))
        self.pushButton_7.setMaximumSize(QtCore.QSize(16777215, 32))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(43,162,239,125);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:15px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:14px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 18px \"Microsoft YaHei\";\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgba(43,162,239,80%);\n"
"    border:2px outset rgba(36,36,36,0);\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color:rgba(43,162,239,90%);\n"
"    border:4px outset rgba(36,36,36,0);\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_15 = QtWidgets.QFrame(self.frame_12)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 431, 171))
        self.frame_15.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit.setGeometry(QtCore.QRect(330, 40, 61, 21))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.frame_15)
        self.label.setGeometry(QtCore.QRect(300, 40, 21, 16))
        self.label.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_15)
        self.label_2.setGeometry(QtCore.QRect(300, 70, 21, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        self.label_3.setGeometry(QtCore.QRect(300, 0, 111, 41))
        self.label_3.setStyleSheet("QLabel{\n"
"    color:rgba(255, 255, 255);\n"
"    font-size:10px;\n"
"    font-style:italic;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";    \n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_15)
        self.label_4.setGeometry(QtCore.QRect(300, 100, 21, 20))
        self.label_4.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame_15)
        self.label_5.setGeometry(QtCore.QRect(300, 130, 21, 16))
        self.label_5.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_5.setObjectName("label_5")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_2.setGeometry(QtCore.QRect(330, 70, 61, 21))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_3.setGeometry(QtCore.QRect(330, 100, 61, 21))
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_15)
        self.lineEdit_4.setGeometry(QtCore.QRect(330, 130, 61, 21))
        self.lineEdit_4.setStyleSheet("QLineEdit{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255,255,255, 35%);\n"
"    border:0px outset rgb(255,255,255);\n"
"    border-radius:10px;\n"
"    text-align:center center;\n"
"    margin-right:3px;\n"
"    margin-bottom:0px;\n"
"    font-size:13px;\n"
"    font:13px \"Microsoft YaHei\";\n"
"}")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setGeometry(QtCore.QRect(400, 40, 21, 16))
        self.label_6.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setGeometry(QtCore.QRect(400, 70, 21, 16))
        self.label_7.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_15)
        self.label_8.setGeometry(QtCore.QRect(400, 100, 21, 16))
        self.label_8.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_15)
        self.label_9.setGeometry(QtCore.QRect(400, 130, 21, 16))
        self.label_9.setStyleSheet("QLabel{\n"
"    background-color: rgba(255, 255, 255, 0%);\n"
"    color:rgb(255, 255, 255);\n"
"    font-size:13px;\n"
"    font-weight:bold;\n"
"    font:bold 13px \"Microsoft YaHei\";\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setGeometry(QtCore.QRect(10, 220, 431, 441))
        self.frame_13.setStyleSheet("QFrame{\n"
"    background-color: rgba(255, 255, 255,10%);\n"
"    border-radius:20px\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1101, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "创建星球"))
        self.pushButton_5.setText(_translate("MainWindow", "选择星球"))
        self.pushButton_6.setText(_translate("MainWindow", "删除星球"))
        self.pushButton_7.setText(_translate("MainWindow", "规划"))
        self.label.setText(_translate("MainWindow", "AP"))
        self.label_2.setText(_translate("MainWindow", "PE"))
        self.label_3.setText(_translate("MainWindow", "轨道信息"))
        self.label_4.setText(_translate("MainWindow", "Δt"))
        self.label_5.setText(_translate("MainWindow", "H"))
        self.label_6.setText(_translate("MainWindow", "km"))
        self.label_7.setText(_translate("MainWindow", "km"))
        self.label_8.setText(_translate("MainWindow", "s"))
        self.label_9.setText(_translate("MainWindow", "km"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
